# Generated by Django 3.1.1 on 2020-09-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('CiudadId', models.AutoField(primary_key=True, serialize=False)),
                ('CiudadNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picoplaca',
            fields=[
                ('DigitoplacaId', models.AutoField(primary_key=True, serialize=False)),
                ('DiaSemana', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('FechaEntrada', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
